### ISSUE TITLE
L2 Broadcast input array error; NewRhoHyper

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#151]
Setup: pySAS data sample, full-FRM, M99, SimSpec, Aqua convolution. 

Error falls just after Alexis' new ADERU printout, L1787 ProcessL2.py and occurs during processing of the second ensemble after the first ensemble processed without error.

Output:
ADERU HYPER
Perform similarity spectrum residual NIR subtraction.
offset(rrs) = -1.0488817976896718e-05; offset(nLw) = -0.03426392120348634
Bad NIR Correction. Revert to No NIR correction.
Processing MODISA
Convolving MODIS Aqua (ir)radiances in the slice
80 spectra in slice (ensemble).
8 spectra remaining in slice to average after filtering to lowest 10.0%.
Calculating M99 glint correction with complete LUT
Calculating Zhang glint correction.
Zhang17 Elapsed Time: 15.7 s
Reading : Data/hybrid_reference_spectrum_p1nm_resolution_c2020-09-21_with_unc.nc
FRM Processing: ES
Running for many wavelengths - this may take a long time
Running for many wavelengths - this may take a long time
Running for many wavelengths - this may take a long time
Running for many wavelengths - this may take a long time
Running for many wavelengths - this may take a long time
Running for many wavelengths - this may take a long time
FRM Processing: LI
FRM Processing: LT
Uncertainty Update Elapsed Time: 37.7 s
ADERU HYPER
Traceback (most recent call last):
  File "/Users/daurin/GitRepos/HyperCP/Main.py", line 546, in multi2Clicked
    self.processMulti(2)
  File "/Users/daurin/GitRepos/HyperCP/Main.py", line 540, in processMulti
    Controller.processFilesMultiLevel(self.outputDirectory,fileNames, calibrationMap, flag_Trios)
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 816, in processFilesMultiLevel
    Controller.processSingleLevel(pathOut, fp, calibrationMap, 'L2', flag_Trios)
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 737, in processSingleLevel
    root = Controller.processL2(root,outFilePath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 449, in processL2
    node = ProcessL2.processL2(root,station)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 2282, in processL2
    if not ProcessL2.stationsEnsemblesReflectance(node, root,station):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 2175, in stationsEnsemblesReflectance
    if not ProcessL2.ensemblesReflectance(node, sasGroup, referenceGroup, ancGroup, uncGroup, esRawGroup,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 1788, in ensemblesReflectance
    ProcessL2.spectralReflectance(node, sensor, timeObj, xSlice, F0_hyper, F0_unc, rhoScalar, rhoVec, waveSubset, xUNC)
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 572, in spectralReflectance
    newRhoHyper.columnsToDataset()
  File "/Users/daurin/GitRepos/HyperCP/Source/HDFDataset.py", line 143, in columnsToDataset
    self.data[k] = v
    ~~~~~~~~~^^^
ValueError: could not broadcast input array from shape (3,) into shape (2,)
2024-04-03 09:12:59.522 python[3108:32556] IMKClient Stall detected, *please Report* your user scenario attaching a spindump (or sysdiagnose) that captures the problem - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (128.92 secs).

**Comment by oceancolorcoder** [comment]
Fixed with PR #154
