### ISSUE TITLE
Issue with SeaBASS output

### ISSUE THREAD

**Issue by juanchossn** [nasa/HyperCP#164]
When running sample pySAS in factory mode (configuration set to default) I get:

Output SeaBASS for HDF: 
/tcenas/s3optcal/workdata/ocean_colour/HyperCP/HyperCP_tests/Sample_Data/SeaBird_pySAS/L2/FRM4SOC2_FICE22_NASA_20220719_080000_L2.hdf
Traceback (most recent call last):
  File "/tcenas/s3optcal/workdata/ocean_colour/HyperCP/HyperCP/Main.py", line 492, in singleL2Clicked
    self.processSingle('L2')
  File "/tcenas/s3optcal/workdata/ocean_colour/HyperCP/HyperCP/Main.py", line 464, in processSingle
    Controller.processFilesSingleLevel(self.outputDirectory,fileNames, calibrationMap, level, flag_Trios)
  File "/tcenas/s3optcal/workdata/ocean_colour/HyperCP/HyperCP/Source/Controller.py", line 871, in processFilesSingleLevel
    Controller.processSingleLevel(pathOut, fp, calibrationMap, level, flag_Trios)
  File "/tcenas/s3optcal/workdata/ocean_colour/HyperCP/HyperCP/Source/Controller.py", line 755, in processSingleLevel
    SeaBASSWriter.outputTXT_Type2(outFilePath)
  File "/tcenas/s3optcal/workdata/ocean_colour/HyperCP/HyperCP/Source/SeaBASSWriter.py", line 507, in outputTXT_Type2
    headerBlock = SeaBASSWriter.formatHeader(fp,root, level='2')
  File "/tcenas/s3optcal/workdata/ocean_colour/HyperCP/HyperCP/Source/SeaBASSWriter.py", line 58, in formatHeader
    headerBlock['comments'] = headerBlock['comments'] + f'\n! DateTime Processed = {time.asctime()}'
KeyError: 'comments'

**Comment by oceancolorcoder** [comment]
Bad sample .hdr file removed from repo.
