### ISSUE TITLE
Error with comet _maths and negative values

### ISSUE THREAD

**Issue by jaanus123** [nasa/HyperCP#172]
The error I'm getting during L2 processing step:
ValueError: comet_maths.generate_sample: u_x cannot have any negative values

**Comment by oceancolorcoder** [comment]
@jaanus123 Can you please confirm you are still getting this error after the latest updates? If so, please include the following details:

Instrument: SeaBird or TriOS
Regime: Default, Class, or Full (in L1B)
More of the error output to include the line in ProcessL2.py called, etc.

Thanks.

**Comment by jaanus123** [comment]
@oceancolorcoder Hey, yes, the error persists
Instrument: TriOS
Regime: Class-based
Error message:
Traceback (most recent call last):
  File "C:\Users\ianandre\Desktop\HyperCP\Main.py", line 546, in multi2Clicked
    self.processMulti(2)
  File "C:\Users\ianandre\Desktop\HyperCP\Main.py", line 540, in processMulti
    Controller.processFilesMultiLevel(self.outputDirectory,fileNames, calibrationMap, flag_Trios)
  File "C:\Users\ianandre\Desktop\HyperCP\Source\Controller.py", line 816, in processFilesMultiLevel
    Controller.processSingleLevel(pathOut, fp, calibrationMap, 'L2', flag_Trios)
  File "C:\Users\ianandre\Desktop\HyperCP\Source\Controller.py", line 737, in processSingleLevel
    root = Controller.processL2(root,outFilePath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ianandre\Desktop\HyperCP\Source\Controller.py", line 449, in processL2
    node = ProcessL2.processL2(root,station)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ianandre\Desktop\HyperCP\Source\ProcessL2.py", line 2286, in processL2
    if not ProcessL2.stationsEnsemblesReflectance(node, root,station):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ianandre\Desktop\HyperCP\Source\ProcessL2.py", line 2179, in stationsEnsemblesReflectance
    if not ProcessL2.ensemblesReflectance(node, sasGroup, referenceGroup, ancGroup, uncGroup, esRawGroup,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ianandre\Desktop\HyperCP\Source\ProcessL2.py", line 1761, in ensemblesReflectance
    xUNC.update(instrument.rrsHyperUNC(uncGroup, rhoScalar, rhoVec, rhoUNC, waveSubset, xSlice))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ianandre\Desktop\HyperCP\Source\ProcessInstrumentUncertainties.py", line 804, in rrsHyperUNC
    ltDeltaBand = Convolve.band_Conv_Uncertainty(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ianandre\Desktop\HyperCP\Source\Uncertainty_Analysis.py", line 349, in band_Conv_Uncertainty
    return self.MCP.propagate_standard(func,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ianandre\AppData\Local\anaconda3\envs\hypercp\Lib\site-packages\punpy\mc\mc_propagation.py", line 559, in propagate_standard
    MC_x = self.generate_MC_sample(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ianandre\AppData\Local\anaconda3\envs\hypercp\Lib\site-packages\punpy\mc\mc_propagation.py", line 618, in generate_MC_sample
    MC_data[i] = cm.generate_sample(
                 ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ianandre\AppData\Local\anaconda3\envs\hypercp\Lib\site-packages\comet_maths\generate_sample\generate_sample.py", line 63, in generate_sample
    raise ValueError(
ValueError: comet_maths.generate_sample: u_x cannot have any negative values

Thanks for your quick response!

**Comment by oceancolorcoder** [comment]
@jaanus123 This should be resolved with commit 6ca711ac36811bccd8f4d17f7ad1c79d4143bff5 in the dev branch. It has not been pushed to the master branch yet.

If you need it now, please use the dev branch or let us know and we can promote dev to master.
