### ISSUE TITLE
Indexerror at L1B->L1BQC - possibly due to long station time

### ISSUE THREAD

**Issue by jaanus123** [nasa/HyperCP#173]
Error message given:

Remove IRRADIANCE Data
   Length of dataset prior to removal 279 long
   Length of dataset after removal 265 long: 5% removed
Remove RADIANCE Data
   Length of dataset prior to removal 279 long
   Length of dataset after removal 265 long: 5% removed
Remove ANCILLARY Data
   Length of dataset prior to removal 279 long
   Length of dataset after removal 265 long: 5% removed
Remove ES_L1AQC Data
   Length of dataset prior to removal 279 long
Traceback (most recent call last):
  File "C:\Users\ianandre\Desktop\HyperCP\main.py", line 546, in multi2Clicked
    self.processMulti(2)
  File "C:\Users\ianandre\Desktop\HyperCP\main.py", line 540, in processMulti
    Controller.processFilesMultiLevel(self.outputDirectory,fileNames, calibrationMap, flag_Trios)
  File "C:\Users\ianandre\Desktop\HyperCP\Source\Controller.py", line 812, in processFilesMultiLevel
    if Controller.processSingleLevel(pathOut, fp, calibrationMap, 'L1BQC', flag_Trios):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ianandre\Desktop\HyperCP\Source\Controller.py", line 627, in processSingleLevel
    root = Controller.processL1bqc(inFilePath, outFilePath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ianandre\Desktop\HyperCP\Source\Controller.py", line 423, in processL1bqc
    root = ProcessL1bqc.processL1bqc(root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ianandre\Desktop\HyperCP\Source\ProcessL1bqc.py", line 696, in processL1bqc
    if not ProcessL1bqc.QC(node):
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ianandre\Desktop\HyperCP\Source\ProcessL1bqc.py", line 638, in QC
    Utilities.filterData(esGroup,badTimes,'L1AQC')
  File "C:\Users\ianandre\Desktop\HyperCP\Source\Utilities.py", line 934, in filterData
    group.datasetDeleteRow(rowsToDelete)
  File "C:\Users\ianandre\Desktop\HyperCP\Source\HDFGroup.py", line 28, in datasetDeleteRow
    ds.data = np.delete(ds.data, (i), axis=0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 180, in delete
  File "C:\Users\ianandre\AppData\Local\anaconda3\envs\hypercp\Lib\site-packages\numpy\lib\function_base.py", line 5156, in delete
    raise IndexError(
IndexError: index 249 is out of bounds for axis 0 with size 246

**Comment by oceancolorcoder** [comment]
Odd. Please post the following on a cloud server we can reach:
*TriOS triplet factory cal files
*TriOS triplet raw files from collection causing the error
*Ancillary SeaBASS file

I will try to reproduce the error to troubleshoot. Also, which L1B regime are you using (Default, Class, Full)?

**Comment by jaanus123** [comment]
@oceancolorcoder  Sorry for the delay. I have added the files to this onedrive [HERE](https://tartuulikool-my.sharepoint.com/:f:/g/personal/ianandre_ut_ee/EhniTD0ZVflHjJ1F1a3Xq0ABA9Yl3Umlume_pFhI9CjGhQ?email=dirk.a.aurin%40nasa.gov&e=QKlePk)
I have been using the class-based approach.

**Comment by oceancolorcoder** [comment]
@jaanus123 thanks for pushing the data up. We will take a look and get back to you.

**Comment by oceancolorcoder** [comment]
Nice sleuthing, Alexis. Thanks. PR merged. Closing issue.
