### ISSUE TITLE
Add DALEC platform (medium term issue)

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#185]
Insitu Marine Optics (IMO) DALEC platform is to be added in 2024. This will include a RAW->L1A interpreter and provisions for instrument-specific and class-based corrections and uncertainties based on forthcoming instrument characterizations.

**Comment by oceancolorcoder** [comment]
@mabdelmegidjr I tested the latest PR changes on my DALEC dataset and got the following error at L1A processing:

`

> Files: (['/Users/daurin/Projects/HyperPACE/field_data/DALEC/NF2405_VIIRS/raw/DALEC_12_2024-05-19_232814Z.TXT'], 'All Files (*)') Process Calibration Files Output Directory: /Users/daurin/Projects/HyperPACE/field_data/DALEC/NF2405_VIIRS dalec_12_2024-05-19_232814z.txt does not match expected input level for outputing L1A

`

Appears related to the Controller.processFilesSingleLevel check for raw file extension at L931. I tried adding 'txt' to the search string list (L893) to get past that and got the following error:

`

> Processing: /Users/daurin/Projects/HyperPACE/field_data/DALEC/NF2405_VIIRS/raw/DALEC_12_2024-05-19_232814Z.TXT Process Single Level ProcessL1a Traceback (most recent call last): File "/Users/daurin/GitRepos/HyperCP/Main.py", line 512, in singleL1aClicked self.processSingle("L1A") File "/Users/daurin/GitRepos/HyperCP/Main.py", line 493, in processSingle Controller.processFilesSingleLevel( File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 939, in processFilesSingleLevel Controller.processSingleLevel(pathOut, fp, calibrationMap, level)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 600, in processSingleLevel root, outFFPs = Controller.processL1a(inFilePath, outFilePath, calibrationMap) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 314, in processL1a root = ProcessL1aDALEC.processL1a(inFilePath, calibrationMap) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL1aDALEC.py", line 48, in processL1a metadata,data=ProcessL1aDALEC.read_data(fp) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL1aDALEC.py", line 216, in read_data data = pd.read_csv(inputfile, skiprows=flag_data+2, names=data_hdr) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/anaconda3/envs/hypercp/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/opt/anaconda3/envs/hypercp/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/opt/anaconda3/envs/hypercp/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv return _read(filepath_or_buffer, kwds) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/anaconda3/envs/hypercp/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read return parser.read(nrows) ^^^^^^^^^^^^^^^^^^ File "/opt/anaconda3/envs/hypercp/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1778, in read ) = self._engine.read(  # type: ignore[attr-defined] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/anaconda3/envs/hypercp/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 230, in read chunks = self._reader.read_low_memory(nrows) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "pandas/_libs/parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory File "pandas/_libs/parsers.pyx", line 866, in pandas._libs.parsers.TextReader._read_rows File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows File "pandas/_libs/parsers.pyx", line 1973, in pandas._libs.parsers.raise_parser_error pandas.errors.ParserError: Error tokenizing data. C error: Expected 212 fields in line 99389, saw 344

`

Raw and cal files available on Box

**Comment by riva-henggu** [comment]
@oceancolorcoder
Please delete line 99389 of the input file, and run it again. I got the similar error when I first ran DALEC_12_2024-05-21_003340Z_trimmed.TXT.

INFO:root:Running from source
MainConfig - Load Config
MainConfig - Refresh or create from default Config
Main - popQueryCheckBoxUpdate
MainConfig - Save Config
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.
MainConfig: Configuration file changed to:  sample_dalec.cfg
Process Single-Level
MainConfig - Save Config
ConfigFile - Create Default Config, or fill in newly added parameters with default values.
SeaBASSHeader - Create Default SeaBASSHeader
SeaBASSHeader - refreshCalibrationFiles
qt.glx: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
No XVisualInfo for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize -1, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize -1, stencilBufferSize -1, samples -1, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)
Falling back to using screens root_visual.
Files: (['/data2/public/HyperCP_nasa/Data/Sample_Data/Dalec/DALEC_12_2024-05-21_003340Z_trimmed.TXT'], 'All Files (*)')
Process Calibration Files
Output Directory: /data2/public/HyperCP_nasa/Data
Processing: /data2/public/HyperCP_nasa/Data/Sample_Data/Dalec/DALEC_12_2024-05-21_003340Z_trimmed.TXT
Process Single Level
ProcessL1a
Traceback (most recent call last):
  File "/data2/public/HyperCP_nasa/Main.py", line 509, in singleL1aClicked
    self.processSingle("L1A")
  File "/data2/public/HyperCP_nasa/Main.py", line 490, in processSingle
    Controller.processFilesSingleLevel(
  File "/data2/public/HyperCP_nasa/Source/Controller.py", line 944, in processFilesSingleLevel
    Controller.processSingleLevel(pathOut, fp, calibrationMap, level)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/public/HyperCP_nasa/Source/Controller.py", line 608, in processSingleLevel
    root, outFFPs = Controller.processL1a(inFilePath, outFilePath, calibrationMap)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/public/HyperCP_nasa/Source/Controller.py", line 318, in processL1a
    root = ProcessL1aDALEC.processL1a(inFilePath, calibrationMap)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/public/HyperCP_nasa/Source/ProcessL1aDALEC.py", line 48, in processL1a
    metadata,data=ProcessL1aDALEC.read_data(fp)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/public/HyperCP_nasa/Source/ProcessL1aDALEC.py", line 273, in read_data
    data = pd.read_csv(inputfile, skiprows=flag_data+2, names=data_hdr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/public/apps/miniconda3/envs/hypercp/lib/python3.11/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/public/apps/miniconda3/envs/hypercp/lib/python3.11/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/public/apps/miniconda3/envs/hypercp/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/public/apps/miniconda3/envs/hypercp/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/data/public/apps/miniconda3/envs/hypercp/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/public/apps/miniconda3/envs/hypercp/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 866, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1973, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 212 fields in line 8859, saw 261

**Comment by riva-henggu** [comment]
This problem has been fixed. The L1A processing will skip the corrupted lines. I processed the same file:

Files: (['/data2/public/HyperCP_nasa/Data/Sample_Data/Dalec/DALEC_12_2024-05-19_232814Z.TXT'], 'All Files (*)')
Process Calibration Files
Output Directory: /data2/public/HyperCP_nasa/Data
Processing: /data2/public/HyperCP_nasa/Data/Sample_Data/Dalec/DALEC_12_2024-05-19_232814Z.TXT
Process Single Level
ProcessL1a
**Skipping line 99389: expected 212 fields, saw 344

Skipping line 121505: expected 212 fields, saw 350

Skipping line 225217: expected 212 fields, saw 248**

MainConfig - Load Config
MainConfig - Refresh or create from default Config
ProcessL1a.processL1a: 21-Jan-2025 15:13:44
Process Single Level: /data2/public/HyperCP_nasa/Data/L1A/DALEC_12_2024-05-19_232814Z_L1A.hdf - SUCCESSFUL
processFilesSingleLevel, single file - DONE

**Comment by oceancolorcoder** [comment]
Tested latest PR on nasa/dalec with VIIRS_Validation 2024 DALEC data:

![Image](https://github.com/user-attachments/assets/342272d7-4977-471b-8e43-ee1582601756)

Process Single-Level
MainConfig - Save Config
ConfigFile - Create Default Config, or fill in newly added parameters with default values.
Files: (['/Users/daurin/Projects/HyperPACE/field_data/DALEC/NF2405_VIIRS/raw/DALEC_12_2024-05-19_232814Z.TXT'], 'All Files (*)')
Process Calibration Files
Output Directory: /Users/daurin/Projects/HyperPACE/field_data/DALEC/NF2405_VIIRS
dalec_12_2024-05-19_232814z.txt does not match expected input level for outputing L1A
Time elapsed: 0 minutes
Process Single-Level
MainConfig - Save Config
ConfigFile - Create Default Config, or fill in newly added parameters with default values.
Files: (['/Users/daurin/Projects/HyperPACE/field_data/DALEC/NF2405_VIIRS/raw/DALEC_12_2024-05-21_003340Z.TXT'], 'All Files (*)')
Process Calibration Files
Output Directory: /Users/daurin/Projects/HyperPACE/field_data/DALEC/NF2405_VIIRS
dalec_12_2024-05-21_003340z.txt does not match expected input level for outputing L1A
Time elapsed: 0 minutes

**Comment by oceancolorcoder** [comment]
@riva-henggu 
Just tested locally on DALEC_17_2025-02-14_175742Z and had an error in PL1AQC trying to filterData on the CAL_COEF group:
 
Percentage of data out of Relative Solar Azimuth bounds: 3 %
Eliminate combined filtered data from datasets.*****************************
Remove CAL_COEF Data
1
Traceback (most recent call last):
  File "/Users/daurin/GitRepos/HyperCP/Main.py", line 519, in singleL1aqcClicked
    self.processSingle("L1AQC")
  File "/Users/daurin/GitRepos/HyperCP/Main.py", line 497, in processSingle
    Controller.processFilesSingleLevel(
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 945, in processFilesSingleLevel
    Controller.processSingleLevel(pathOut, fp, calibrationMap, level)               
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 661, in processSingleLevel
    root = Controller.processL1aqc(inFilePath, outFilePath, calibrationMap, ancillaryData)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 362, in processL1aqc
    root = ProcessL1aqc.processL1aqc(root, calibrationMap, ancillaryData)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL1aqc.py", line 1070, in processL1aqc
    node = ProcessL1aqc.filterBadTimes(node,badTimes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL1aqc.py", line 30, in filterBadTimes
    fractionRemoved = ProcessL1aqc.filterData(gp, badTimes)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL1aqc.py", line 75, in filterData
    timeStamp = group.getDataset("DATETIME").data
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

**Comment by oceancolorcoder** [comment]
DALEC integration released with v1.2.13
