### ISSUE TITLE
Propagation of 6S

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#190]
6S model results are only propagated in Full, but to apply the new cloud flag in L1BQC, we need 6S (Es) in Default and Class.

**Comment by fecgiannini** [comment]
Hi,
I am runing Non-FRM Class-based (seabird) and I find the error below, that it seems related somehow with this 6S model.
I was able to process my data during the FICE, but now that I updated the hyperCP, I keep getting this error:
Any thought?
Tks

ProcessL2: C:\Users\fecgi\OneDrive\FICE_2024\RENOMO_stuff\output_19jul24\L1BQC\RENOMOSR_SR15_1357_L1BQC.hdf
stationsEnsemblesReflectance
Traceback (most recent call last):
  File "C:\Users\fecgi\Documents\HyperCP\Main.py", line 546, in multi2Clicked
    self.processMulti(2)
  File "C:\Users\fecgi\Documents\HyperCP\Main.py", line 540, in processMulti
    Controller.processFilesMultiLevel(self.outputDirectory,fileNames, calibrationMap, flag_Trios)
  File "C:\Users\fecgi\Documents\HyperCP\Source\Controller.py", line 815, in processFilesMultiLevel
    Controller.processSingleLevel(pathOut, fp, calibrationMap, 'L2', flag_Trios)
  File "C:\Users\fecgi\Documents\HyperCP\Source\Controller.py", line 736, in processSingleLevel
    root = Controller.processL2(root,outFilePath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fecgi\Documents\HyperCP\Source\Controller.py", line 449, in processL2
    node = ProcessL2.processL2(root,station)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fecgi\Documents\HyperCP\Source\ProcessL2.py", line 2293, in processL2
    if not ProcessL2.stationsEnsemblesReflectance(node, root,station):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fecgi\Documents\HyperCP\Source\ProcessL2.py", line 2019, in stationsEnsemblesReflectance
    rootCopy.getGroup('PY6S_MODEL').copy(root.getGroup('PY6S_MODEL'))
  File "C:\Users\fecgi\Documents\HyperCP\Source\HDFGroup.py", line 16, in copy
    self.copyAttributes(gp)
  File "C:\Users\fecgi\Documents\HyperCP\Source\HDFGroup.py", line 22, in copyAttributes
    for k,v in gp.attributes.items():
               ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attributes'

**Comment by oceancolorcoder** [comment]
@fecgiannini Apologies, I believe this was a bug that we fixed in our development branch, but had not merged into the master branch (the primary distribution). It has now been merged in. Please try
`git pull`
and see if that does not fix the problem for you.

**Comment by fecgiannini** [comment]
Fixed! Thanks

It seems now that, during the uncertainties propagation step, I am getting that error related to the number of bands in my instrument calibration set up.
"ValueError: operands could not be broadcast together with shapes (100,138) (137,)"
I do remember that this was fixed, not sure what happened.
(Different topic though, should I post this somewhere else?)

**Comment by oceancolorcoder** [comment]
Maybe, but let's test something first. Did you start again at raw (L0) data after updating?

**Comment by fecgiannini** [comment]
Yes, I did.
Then I tried to run it with Mobley's model and got this error above.
Now I switched to Zhangs and the processing is stuck for minutes, it says that hyperCP is "Not Responding".
I will restart everything again, then I will let you know.

**Comment by fecgiannini** [comment]
Yes, I did.
Multi-level: Raw (BIN) ---> L2(HDF5)
Also a new output directory to make sure.

This is the full error message:

Reading : Data/hybrid_reference_spectrum_p1nm_resolution_c2020-09-21_with_unc.nc
Traceback (most recent call last):
  File "C:\Users\fecgi\Documents\HyperCP\Main.py", line 546, in multi2Clicked
    self.processMulti(2)
  File "C:\Users\fecgi\Documents\HyperCP\Main.py", line 540, in processMulti
    Controller.processFilesMultiLevel(self.outputDirectory,fileNames, calibrationMap, flag_Trios)
  File "C:\Users\fecgi\Documents\HyperCP\Source\Controller.py", line 815, in processFilesMultiLevel
    Controller.processSingleLevel(pathOut, fp, calibrationMap, 'L2', flag_Trios)
  File "C:\Users\fecgi\Documents\HyperCP\Source\Controller.py", line 736, in processSingleLevel
    root = Controller.processL2(root,outFilePath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fecgi\Documents\HyperCP\Source\Controller.py", line 449, in processL2
    node = ProcessL2.processL2(root,station)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fecgi\Documents\HyperCP\Source\ProcessL2.py", line 2302, in processL2
    if not ProcessL2.stationsEnsemblesReflectance(node, root,station):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fecgi\Documents\HyperCP\Source\ProcessL2.py", line 2193, in stationsEnsemblesReflectance
    if not ProcessL2.ensemblesReflectance(node, sasGroup, referenceGroup, ancGroup, uncGroup, esRawGroup,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fecgi\Documents\HyperCP\Source\ProcessL2.py", line 1741, in ensemblesReflectance
    xSlice.update(instrument.Factory(node, uncGroup, stats))  # update the xSlice dict with uncertianties and samples
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fecgi\Documents\HyperCP\Source\ProcessInstrumentUncertainties.py", line 189, in Factory
    es_unc, li_unc, lt_unc = PropagateL1B.propagate_Instrument_Uncertainty(mean_values, uncertainty)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fecgi\Documents\HyperCP\Source\Uncertainty_Analysis.py", line 144, in propagate_Instrument_Uncertainty
    unc = self.MCP.propagate_random(self.instruments,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fecgi\anaconda3\envs\hypercp\Lib\site-packages\punpy\mc\mc_propagation.py", line 123, in propagate_random
    return self.propagate_standard(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fecgi\anaconda3\envs\hypercp\Lib\site-packages\punpy\mc\mc_propagation.py", line 559, in propagate_standard
    MC_x = self.generate_MC_sample(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fecgi\anaconda3\envs\hypercp\Lib\site-packages\punpy\mc\mc_propagation.py", line 618, in generate_MC_sample
    MC_data[i] = cm.generate_sample(
                 ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fecgi\anaconda3\envs\hypercp\Lib\site-packages\comet_maths\generate_sample\generate_sample.py", line 100, in generate_sample
    sample = generate_sample_systematic(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fecgi\anaconda3\envs\hypercp\Lib\site-packages\comet_maths\generate_sample\generate_sample.py", line 324, in generate_sample_systematic
    np.dot(
ValueError: operands could not be broadcast together with shapes (100,138) (137,)

**Comment by oceancolorcoder** [comment]
@fecgiannini I have opened a new issue #219. Because of the where this is I need to refer it to NPL who may not see it until next week.

**Comment by oceancolorcoder** [comment]
• When trying to calculate 6S from the Class or Default regime:

		Running for many wavelengths - this may take a long time
		WARNING:root:irr_direct contains NaN values at: [443.05 590.05 633.45 670.13]
		WARNING:root:irr_diffuse contains NaN values at: [443.05 590.05 633.45 670.13]
		WARNING:root:irr_env contains NaN values at: [443.05 590.05 633.45 670.13]
		Running for many wavelengths - this may take a long time
		WARNING:root:irr_direct contains NaN values at: []
		WARNING:root:irr_diffuse contains NaN values at: []
		WARNING:root:irr_env contains NaN values at: [], etc…

	• And yet, res_py6s is populated.
		
 Does ProcessL1b_FRMCal.get_direct_irradiance_ratio(node, 'ES') work properly if it does not follow after ProcessL1b_FRMCal.processL1b_SeaBird?

**Comment by oceancolorcoder** [comment]
Resolved with [ffeb94a](https://github.com/nasa/HyperCP/commit/ffeb94a42d80ca44302aa9f7992f2651b3a15dbb)
