### ISSUE TITLE
Key error headerBlock['comments']

### ISSUE THREAD

**Issue by raphidoc** [nasa/HyperCP#226]
I'm running in this error in two places in the code,
The PDFreport.py:

```
Traceback (most recent call last):
  File "/home/raphael/PycharmProjects/HyperCP/run_Sample_Data.py", line 228, in <module>
    worker(fp_input_files)       
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/PycharmProjects/HyperCP/run_Sample_Data.py", line 188, in worker
    run_Command(file)
  File "/home/raphael/PycharmProjects/HyperCP/run_Sample_Data.py", line 138, in run_Command
    Command(
  File "/home/raphael/PycharmProjects/HyperCP/Main.py", line 649, in __init__
    Controller.processFilesMultiLevel(self.outputDirectory,[inputFile], calibrationMap, flag_Trios)
  File "/home/raphael/PycharmProjects/HyperCP/Source/Controller.py", line 790, in processFilesMultiLevel
    if Controller.processSingleLevel(pathOut, fp, calibrationMap, 'L1A', flag_Trios):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/raphael/PycharmProjects/HyperCP/Source/Controller.py", line 759, in processSingleLevel
    Controller.writeReport(fileName, pathOut, outFilePath, level, inFilePath)
  File "/home/raphael/PycharmProjects/HyperCP/Source/Controller.py", line 104, in writeReport
    pdf.print_chapter('L1A', 'Process RAW to L1A', inLog, inPlotPath, fileName, root)
  File "/home/raphael/PycharmProjects/HyperCP/Source/PDFreport.py", line 498, in print_chapter
    self.chapter_body(inLog, headerBlock, level, inPlotPath, filebasename, root)
  File "/home/raphael/PycharmProjects/HyperCP/Source/PDFreport.py", line 313, in chapter_body
    comments1 = headerBlock['comments'].split('!')
                ~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'comments'
```

And the SeaBASSWriter.py :

```  
File "/home/raphael/PycharmProjects/HyperCP/Source/SeaBASSWriter.py", line 70, in formatHeader
    headerBlock['comments'] = headerBlock['comments'] + f'\n! DateTime Processed = {time.asctime()}'
  ^^^^^^^^^^^^^^^^^
KeyError: 'comments'
```

Any idea where this comes from?

**Comment by oceancolorcoder** [comment]
Check the SeaBASS header contents from the Config window gui. Try re-saving it there. Check the ConfigFile.settings pointer to the SeaBASS header file in the Config folder.

**Comment by raphidoc** [comment]
Thanks, re-saving the SeaBASS.hdr from the GUI did the trick!
