### ISSUE TITLE
PACE-PAX PIU Division by zero

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#275]
@ARamsay17 
Same configuration as #274. L1BQC file on the Box.

```
ProcessL2: /Users/daurin/Projects/HyperPACE/field_data/HyperSAS/PACE-PAX/L1BQC/PACE-PAX_PACE-PAX_20240915_220000_L1BQC.hdf
stationsEnsemblesReflectance
Binning datasets to ensemble time interval.
Convolving MODIS Aqua (ir)radiances in the slice
6 spectra in slice (ensemble).
Calculating M99 glint correction with complete LUT
Calculating Zhang glint correction.
Zhang17 Elapsed Time: 13.9 s
Reading : Data/hybrid_reference_spectrum_p1nm_resolution_c2020-09-21_with_unc.nc
Uncertainty Update Elapsed Time: 14.1 s
Perform simple residual NIR subtraction.
Processing MODISA
Traceback (most recent call last):
  File "/Users/daurin/GitRepos/HyperCP/Main.py", line 568, in multi2Clicked
    self.processMulti()
  File "/Users/daurin/GitRepos/HyperCP/Main.py", line 561, in processMulti
    Controller.processFilesMultiLevel(
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 865, in processFilesMultiLevel
    Controller.processSingleLevel(pathOut, fp, calibrationMap, 'L2')
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 778, in processSingleLevel
    root = Controller.processL2(root,outFilePath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 460, in processL2
    node = ProcessL2.processL2(root,station)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 2359, in processL2
    if not ProcessL2.stationsEnsemblesReflectance(node, root,station):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 2248, in stationsEnsemblesReflectance
    if not ProcessL2.ensemblesReflectance(node, sasGroup, referenceGroup, ancGroup, 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 1363, in ensemblesReflectance
    stats = instrument.generateSensorStats("SeaBird",
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessInstrumentUncertainties.py", line 113, in generateSensorStats
    output[sensortype] = self.lightDarkStats(
                         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessInstrumentUncertainties.py", line 1270, in lightDarkStats
    std_Light.append(np.sqrt(((N-1)/(N-3))*(np.std(lightData[k]) / np.sqrt(N))**2))
                              ~~~~~^^~~~~
ZeroDivisionError: division by zero
```

**Comment by oceancolorcoder** [comment]
Resolved with PR #284
