### ISSUE TITLE
6S_json returns all zeroes

### ISSUE THREAD

**Issue by oceancolorcoder** [nasa/HyperCP#276]
@raphidoc 
Testing in nasa:6S_json branch yields all zeroes in 6S model results:

![image](https://github.com/user-attachments/assets/fcd9e6ea-0581-42e1-a374-10fc9ef1e85d)

**Comment by raphidoc** [comment]
Hello @oceancolorcoder, so it appears there was a kerfuffle, likely in a merge operation on the 6S_json branch. I fixed the problem, and everything worked fine after testing locally. 
See pull request #288

**Comment by raphidoc** [comment]
Hello @oceancolorcoder, to simplify the review of the 6S_json branch, I propose that you delete the existing one and create a fresh one from dev. After that, I could add the modif I made to the environment file and to the ProcessL1b_FRMCal.py. That way we will be sure not to break anything :)

I found some references regarding the proper way to rebase code before a pull request. I'll write a guide on using git and GitHub to contribute to the project as an internal reference.

**Comment by oceancolorcoder** [comment]
New branch created under the same name.

**Comment by oceancolorcoder** [comment]
@raphidoc  Testing new 6S_json branch today on sample_pySAS data:
![image](https://github.com/user-attachments/assets/e913275a-e8ce-459a-bc23-4bb1e0d130ca)

Results in an error in PIU:
`Calculating M99 glint correction with complete LUT
Calculating Zhang glint correction.
Zhang17 Elapsed Time: 8.2 s
Reading : Data/hybrid_reference_spectrum_p1nm_resolution_c2020-09-21_with_unc.nc
FRM Processing: ES
Traceback (most recent call last):
  File "/Users/daurin/GitRepos/HyperCP/Main.py", line 575, in multi2Clicked
    self.processMulti()
  File "/Users/daurin/GitRepos/HyperCP/Main.py", line 568, in processMulti
    Controller.processFilesMultiLevel(
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 865, in processFilesMultiLevel
    Controller.processSingleLevel(pathOut, fp, calibrationMap, 'L2')
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 738, in processSingleLevel
    Controller.processL2(root, outFilePathStation,station)
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 457, in processL2
    node = ProcessL2.processL2(root,station)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 2363, in processL2
    if not ProcessL2.stationsEnsemblesReflectance(node, root,station):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 2236, in stationsEnsemblesReflectance
    if not ProcessL2.ensemblesReflectance(node, sasGroup, referenceGroup, ancGroup, 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 1816, in ensemblesReflectance
    instrument.FRM(node, uncGroup,
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessInstrumentUncertainties.py", line 1597, in FRM
    direct_ratio, _ = self.interp_common_wvls(np.array(direct_ratio, float), res_sixS['wavelengths'], radcal_wvl)
    ^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)`

**Comment by raphidoc** [comment]
Hi @oceancolorcoder, The above pull request fixes this. I tested it with the sample data (which I should have done before, sorry). I guess it's further proof that a good automated test suite would be beneficial!

**Comment by oceancolorcoder** [comment]
Thanks. I'll take a look shortly and merge it in. Automated application testing is implemented but was still throwing an error associated with the ECMWF API, so it may not have gotten far enough to catch this.

**Comment by oceancolorcoder** [comment]
Tested on pySAS sample file:

![Image](https://github.com/user-attachments/assets/fced1c6f-c14c-49a6-9fa5-d61e0442a2e9)

Calculating Zhang glint correction.
Zhang17 Elapsed Time: 18.4 s
Reading : Data/hybrid_reference_spectrum_p1nm_resolution_c2020-09-21_with_unc.nc
FRM Processing: ES
Traceback (most recent call last):
  File "/Users/daurin/GitRepos/HyperCP/Main.py", line 575, in multi2Clicked
    self.processMulti()
  File "/Users/daurin/GitRepos/HyperCP/Main.py", line 568, in processMulti
    Controller.processFilesMultiLevel(
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 865, in processFilesMultiLevel
    Controller.processSingleLevel(pathOut, fp, calibrationMap, 'L2')
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 738, in processSingleLevel
    Controller.processL2(root, outFilePathStation,station)
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 457, in processL2
    node = ProcessL2.processL2(root,station)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 2363, in processL2
    if not ProcessL2.stationsEnsemblesReflectance(node, root,station):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 2236, in stationsEnsemblesReflectance
    if not ProcessL2.ensemblesReflectance(node, sasGroup, referenceGroup, ancGroup, 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 1816, in ensemblesReflectance
    instrument.FRM(node, uncGroup,
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessInstrumentUncertainties.py", line 1597, in FRM
    direct_ratio, _ = self.interp_common_wvls(np.array(direct_ratio, float), res_sixS['wavelengths'], radcal_wvl)
    ^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)

**Comment by oceancolorcoder** [comment]
Issue resolved with PR #306 

6S_json branch merged into nasa:dev.

User conda environment will need updating using the updated environment.yml file.
