### ISSUE TITLE
Zhang method fail in L2 processing

### ISSUE THREAD

**Issue by AlexisDeru** [nasa/HyperCP#83]
Error when running Zhang instead of Mobley.
Happens at L2 processing:

File "/mount/internal/work-st/projects/tartu-1281/FRM4SOCv2/workspace/aderu/nasa/HyperInSPACE/Source/ProcessL2.py", line 1616, in ensemblesReflectance
    rhoVector, rhoUNC = RhoCorrections.ZhangCorr(WINDSPEEDXSlice,AODXSlice, CloudXSlice, SZAXSlice, SSTXSlice,

File "/mount/internal/work-st/projects/tartu-1281/FRM4SOCv2/workspace/aderu/nasa/HyperInSPACE/Source/RhoCorrections.py", line 170, in ZhangCorr
    rhoDelta = Propagate.zhangWrapper(mean_vals=varlist, uncertainties=ulist,

TypeError: Propagate.zhangWrapper() got an unexpected keyword argument 'mean_vals'

**Comment by oceancolorcoder** [comment]
Resolved as far as I can tell, although I do not know which commit/PR fixed it

**Comment by oceancolorcoder** [comment]
Reopening this issue:

Traceback (most recent call last):
  File "/Users/daurin/GitRepos/HyperCP/Main.py", line 534, in multi2Clicked
    self.processMulti(2)
  File "/Users/daurin/GitRepos/HyperCP/Main.py", line 528, in processMulti
    Controller.processFilesMultiLevel(self.outputDirectory,fileNames, calibrationMap, flag_Trios)
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 805, in processFilesMultiLevel
    Controller.processSingleLevel(pathOut, fp, calibrationMap, 'L2', flag_Trios)
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 727, in processSingleLevel
    root = Controller.processL2(root,outFilePath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/Controller.py", line 439, in processL2
    node = ProcessL2.processL2(root,station)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 2218, in processL2
    if not ProcessL2.stationsEnsemblesReflectance(node, root,station):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 2111, in stationsEnsemblesReflectance
    if not ProcessL2.ensemblesReflectance(node, sasGroup, referenceGroup, ancGroup, uncGroup, esRawGroup,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/daurin/GitRepos/HyperCP/Source/ProcessL2.py", line 1597, in ensemblesReflectance
    rhoVector, rhoUNC = RhoCorrections.ZhangCorr(WINDSPEEDXSlice,AODXSlice, CloudXSlice, SZAXSlice, SSTXSlice,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: RhoCorrections.ZhangCorr() takes 8 positional arguments but 9 were given

**Comment by oceancolorcoder** [comment]
Appears resolved in [e391809](https://github.com/nasa/HyperCP/commit/e39180926ed7ffc039f5e97888b26fb2ed950bba)

Testing to follow.
